### ISSUE TITLE
Throwing errors when LuckPerms is not installed

### ISSUE THREAD

**Issue by CatMe0w** [ActualPlayer/RememberMe#1]
I didn't install LuckPerms in Velocity, but should not it be optional?
The related logs are below.
```
[09:34:27 ERROR]: Some errors occurred whilst posting event ProxyInitializeEvent.
[09:34:27 ERROR]: #1:

java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
        at com.actualplayer.rememberme.RememberMe.onProxyInitialization(RememberMe.java:50) ~[?:?]
        at net.kyori.event.asm.generated.4baa2c5a08.RememberMe-onProxyInitialization-ProxyInitializeEvent-2.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity-proxy-1.0.5-SNAPSHOT-all.jar:1.0.5-SNAPSHOT (git-0c7a9957-b190)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity-proxy-1.0.5-SNAPSHOT-all.jar:1.0.5-SNAPSHOT (git-0c7a9957-b190)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:136) ~[velocity-proxy-1.0.5-SNAPSHOT-all.jar:1.0.5-SNAPSHOT (git-0c7a9957-b190)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$0(VelocityEventManager.java:117) ~[velocity-proxy-1.0.5-SNAPSHOT-all.jar:1.0.5-SNAPSHOT (git-0c7a9957-b190)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:66) ~[velocity-proxy-1.0.5-SNAPSHOT-all.jar:1.0.5-SNAPSHOT (git-0c7a9957-b190)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43) ~[velocity-proxy-1.0.5-SNAPSHOT-all.jar:1.0.5-SNAPSHOT (git-0c7a9957-b190)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
        ... 9 more
```

**Comment by ActualPlayer** [comment]
Thanks for the report, this is now fixed in version 1.2, sorry for the long wait. I have been absent from minecraft for a while.
