### ISSUE TITLE
2.0.0 not even loading on Velocity 3.3.0-SNAPSHOT (git-9d25d309-b400)

### ISSUE THREAD

**Issue by VladOliinyk** [ActualPlayer/RememberMe#11]
```
[07:39:27] [main/ERROR] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Unable to load plugin plugins/Remember.Me-2.0.0.jar
com.velocitypowered.api.plugin.InvalidPluginException: Did not find a valid velocity-plugin.json.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:65) ~[velocity.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[velocity.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:362) ~[velocity.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:239) ~[velocity.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity.jar:3.3.0-SNAPSHOT (git-9d25d309-b400)]
```

**Comment by ActualPlayer** [comment]
Fixed in V2.0.0
